name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/1 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://alzheimer-ece-ntua-healthcare.streamlit.app > /dev/null
